### ISSUE TITLE
Rewrite the API in Django

### ISSUE THREAD

**Issue by keithamoss** [keithamoss/demsausage#46]
# @TODO
- [x] Implement public API endpoints
- [x] Implement admin API endpoints
  - [x] Download polling places as a CSV file ([here](https://docs.djangoproject.com/en/2.1/howto/outputting-csv/), [here](https://stackoverflow.com/questions/15029666/exporting-items-from-a-model-to-csv-django-python), and [here](https://stackoverflow.com/questions/38697529/how-to-return-generated-file-download-with-django-rest-framework))
  - [x] Upload and ingest a polling places CSV file
  - [x] Edit a polling place type
  - [x] Edit a polling place
  - [x] Approve a stall (+ send email)
  - [x] Decline a stall
  - [x] Email opt in/out
  - [x] Trigger Election GeoJSON regeneration
  - [x] Optimise GeoJSON generation (too many db queries per noms?)
  - [x] Mailgun webhooks
  - [x] Cron job to email us nightly
  - [x] Better error handling from DRF to React
- [x] Check for remaining legacy API calls. Remove hard-coded paths.
- [x] Go over PHP code function-by-function to check for any special logic (like is_active had). Remove legacy API code.
- [x] Test Admin and Public sites
- [x] Update and re-run db migration script again
- [x] Squash and nuke all migrations and re-run fresh db setup
- [x] DevOps https://github.com/keithamoss/demsausage-v3/issues/48
- [x] Setup local prod
- [x] Bump Supervisord, UWSGI, Django, and Nginx timeout limits up to account for loading polling places
- [x] Make changes to digitalocean-stack
- [x] Deploy as api2.democracysausage.org
- [x] Tell the API user about forthcoming changes
- [x] Apply and verify Mailgun web hook changes; Verify stall approval emails
- [x] Deploy to PROD
- [x] Deploy as api.democracysausage.org alongside new admin and public sites
- [x] Test Admin and Public sites (check static assets are available)
- [x] Load a test election
- [x] Finish fixing the chance_of_sausage migration
- [x] Get folks to login again. Set `is_staff=True` and `is_superuser=True`.
- [x] Check db backups are working again
- [x] Docker hub and private things in images
- [x] Decommission old PHP api site
- [x] Verify cron is working
- ~CORB~
- Move API to /api
  - [x] Move Sausage API
  - [x] Update cookies for Sausage
- [x] Fix election dates
- [x] Location Enter key bug on Add Stall form
- ~Use a VERSION file (and put app version for backend and frontend in the Redux store so we see it in Sentry.io)~
- [x] CF cache purging on redeploy
- [x] Look over the CloudFlare rules and think about how caching is working through the levels.
- [x] Verify how CloudFlare treats static resources + icons now that we've removed those special page rules
- [x] Did CF cache polling places for use before or did we bypass? What would CF cost to resolve the cookies and page rules issues (if they are still both issues?)
- [CF doesn't like long-running requests](https://support.cloudflare.com/hc/en-us/articles/200171926-Error-524-A-timeout-occurred) (The backend process still completes, but we don't see the logs in response.)
  - [x] Log results to a table using a "job id"
  - ~Use Celery (Move polling place loading; Use for scheduled jobs instead of cron)~
- [x] Tweak cron timing. Arrives at 14:00 - should be 20:00.
- [x] Check login behaviour on mobile
- [x] Include polling place name / premises / stall name in emails to better differentiate from our side

# Enhancements
- [x] Explore [django-rest-swagger](https://django-rest-swagger.readthedocs.io/en/latest/)
- [x] Validate which API endpoints are publicly exposed (e.g. DELETE to purge cache)
- [x] Use Nginx Memcached for GeoJSON to avoid hitting Django at all
