### ISSUE TITLE
Map UI polishing

### ISSUE THREAD

**Issue by keithamoss** [keithamoss/demsausage#69]
We need to incorporate five elements on the main screen:

- Filters (modal?)
- Merch
- Sausagelytics
- Add Stall
- Search Bar

## @TODO
- [ ] Look for inspiration and do some sketching
- [ ] Discuss design with H
- [ ] Revisit icons and discuss with H (e.g. Switch vego to broccoli)

## Inspiration
- Dribble
- Things popping up from bottom like MFP weight selector
- Google Maps on iOS

## Feedback
> I especially like the filterable options, but was hoping you could add a spot in the FAQ (or elsewhere) that explains the icons, as I couldn't distinguish if the vegetable icon means vego options or a flower/plant stall, at least on the mobile site. (I ended up finding out by starting to make a stall and then bailing)

[AB#90](https://dev.azure.com/contentsmaydiffer/cbcb376c-170c-4145-a81c-387d82266f0d/_workitems/edit/90)
